(setq warp-dir (concat dotfiles-dir "tops/"))
(setq warp-table (make-hash-table :test 'equal))

(defun new-warp (name place)
  (let ((warp (concat warp-dir place)))
    (make-directory warp 't)
    (puthash name warp warp-table)))

(new-warp "f" "GSPtools")
(new-warp "unnel" "funnelwhich")
(new-warp "o" "ovenfreak")
(new-warp "popo" "posture")
(new-warp "chirpy" "chirpy")
(new-warp "wp" "wpp")
(new-warp "ord" "ordinary")
(new-warp "court" "court")
(new-warp "tribe" "tribe")
(new-warp "tbooks" "books")
(new-warp "pick" "pickrey")
(new-warp "chiffon" "chiffon")
(new-warp "crunchy" "crunchy")
(new-warp "actiogreen" "actiogreen")
(puthash "home" "~/" warp-table)
