(setq warp-dir (concat dotfiles-dir "tops/"))
(setq warp-table (make-hash-table :test 'equal))

(defun new-warp (name place)
  (let ((warp (concat warp-dir place)))
    (make-directory warp 't)
    (puthash name warp warp-table)))

(new-warp "nims" "pylonshello")
(new-warp "ptx" "ptx")
(new-warp "oduslist" "oduslist")
(new-warp "brownstone" "brownstone")
(new-warp "brev" "breviloquention")
(new-warp "stomp" "stomping-ground")
(new-warp "dswap" "dswap")
(new-warp "scg" "scg")
(new-warp "cos318" "cos318")
(new-warp "iw" "iw")
(puthash "home" "~/" warp-table)
